{% set name = "h5coro" %}
{% set version = "1.0.4" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/h5coro-{{ version }}.tar.gz
  sha256: e29ec6fe0fde2c3f27aedcaaf5af7aded7552b1d6fa219f20e1367b0e75ee049

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - boto3
    - earthaccess >=0.5.0
    - requests
    - xarray

test:
  imports:
    - h5coro
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ICESat2-SlideRule/h5coro/
  summary: Python package for reading HDF5 data from S3
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jpswinski
    - elidwa
